### ISSUE TITLE
LockError using flask-zodb with mod_wsgi

### ISSUE THREAD

**Issue by esaurito** [dag/flask-zodb#2]
I have a problem using [flask-zodb](http://readthedocs.org/docs/flask-zodb/en/latest/) in a simple [Flask](http://flask.pocoo.org/) app deployed with `mod_wsgi`.
Every time I try to use the DB for example setting defaults:

```
from flaskext.zodb import zodb, List

db = ZODB(app)
app.config.from_pyfile('settings.py') # here I have defined ZODB_STORAGE = "/home/username/webapps/myapp/htdocs/Data.fs"

@app.before_request
def set_db_defaults():
   if 'entries' not in db:
       db['entries'] = List()
```

or in a view like:

```
@app.route('/add', methods=['POST'])
def add_entry():
   db['entries'].append(request.form)
   flash('New entry was successfully posted')
   return redirect(url_for('show_entries'))
```

I got the following error:

```
[Sat May 19 16:52:30 2012] [error] [client 127.0.0.1]
self._lock_file = LockFile(file_name + '.lock')
[Sat May 19 16:52:30 2012] [error] [client 127.0.0.1]   File
"/home/userame/.virtualenvs/myapp/lib/python2.7/site-packages/zc/lockfile/__init__.py",
line 76, in __init__
[Sat May 19 16:52:30 2012] [error] [client 127.0.0.1]     _lock_file(fp)
[Sat May 19 16:52:30 2012] [error] [client 127.0.0.1]   File
"/home/username/.virtualenvs/myapp/lib/python2.7/site-packages/zc/lockfile/__init__.py",
line 59, in _lock_file
[Sat May 19 16:52:30 2012] [error] [client 127.0.0.1]     raise
LockError("Couldn't lock %r" % file.name)
[Sat May 19 16:52:30 2012] [error] [client 127.0.0.1] LockError:
Couldn't lock '/home/username/webapps/myapp/htdocs/Data.fs.lock'
```

The application works fine in the development enviroment and I do not think there's a premission problem since I tried to set: 

```
ZODB_STORAGE = "/tmp"
```

And the same exception is raised. I can't understand why this happens and how to avoid this kind of error. It's a bug or I'm doing something wrong? On [SO](http://stackoverflow.com/a/10682629/246242) someone told me to use ZEO but I would like to be sure that I'm not doing something wrong before adding another layer of complexity.

**Comment by dag** [comment]
Direct use of FileStorage is not multiprocess-safe, and mod_wsgi typically spawns multiple worker processes. So yes, ZEO is the way to go.

**Comment by esaurito** [comment]
Maybe it's obvious, but I think this should be mentioned in the docs since mod_wsgi is a common setup for flask applications and as far as I can understand setting up ZEO is not so simple. Anyway thank for your help!

**Comment by dag** [comment]
I don't really write any Python these days though. I'd welcome new maintainers of my packages including Flask-ZODB.

**Comment by esaurito** [comment]
I would like to help but I'm not so skilled, maybe I can add a bit of documentation with a pull request as soon as I have time. 
Thank you!
